backend:
  name: github
  repo: mlgamble/mlgamble.github.io
  branch: develop
media_folder: static/assets
public_folder: /assets
collections:
  - name: recipe
    label: Recipe
    folder: pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }