# This is a basic workflow to help you get started with Actions

name: Sync from Google Drive

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pull-to-local:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Pull Google Drive files
      uses: mlgamble/action-google-drive@0.0.1
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        action: download
        args: '-ignore-times mlgamble.github.io src/pages'
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    - name: Check for git changes
      id: git-changes
      run: |
        echo "::set-output name=changes::`git status --porcelain | wc -l | xargs`"
    - uses: mlgamble/action-git@0.0.1
      if: ${{ steps.git-changes.outputs.changes > 0 }}
      with:
        private-key: ${{ secrets.PRIVATE_KEY }}
        public-key: ${{ secrets.PUBLIC_KEY }}
        command: 'git add . && git commit -m "File updates from Google Drive" && git push'
    - name: Trigger rebuild
      if: ${{ steps.git-changes.outputs.changes > 0 }}
      run: |
        curl -L -XPOST \
        -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
        "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" \
        -d '{"event_type": "trigger-rebuild"}' 
  trigger-rebuild:
    runs-on: ubuntu-latest
